#! /bin/sh

if [ -s ~/.Xmodmap ]; then
    xmodmap ~/.Xmodmap
fi

if [ -s ~/.Xresources ]; then
    xrdb ~/.Xresources
fi

nvidia-settings --assign CurrentMetaMode="DPY-2: nvidia-auto-select @2560x1440 +1920+0 {ViewPortIn=2560x1440, ViewPortOut=2560x1440+0+0, ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}, DPY-3: nvidia-auto-select @1920x1080 +0+0 {ViewPortIn=1920x1080, ViewPortOut=1920x1080+0+0, ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}"

killall sxhkd ; sxhkd &
killall polybar
polybar main &
polybar secondary &
killall touchegg ; touchegg &
nitrogen --restore &
killall nm-applet ; nm-applet &

bspc monitor HDMI-0 -d I II III IV V VI
bspc monitor HDMI-1 -d VII VIII IX
# bspc monitor HDMI-1 -d IX X

bspc config border_width         4
bspc config window_gap           0

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc config focus_follows_pointer true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_struts   true
bspc config -m HDMI-0 top_padding 30
bspc config -m HDMI-1 top_padding 25

bspc rule -a Matplotlib state=floating
bspc rule -a Mathpix\ Snipping\ Tool state=floating
bspc rule -a scrcpy state = floating
bspc rule -a Evolution-alarm-notify state = floating
bspc rule -a matplotlib state=floating

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off



